# rm ~/Library/Application\ Support/lazygit/config.yml
# Mac: ln -s ~/dev/dotfiles/lazygit/config.yml ~/Library/Application\ Support/lazygit/config.yml
# Linux: ln -s ~/dev/dotfiles/lazygit/config.yml ~/.config/lazygit/config.yml

# What to do when opening Lazygit outside of a git repo.
# - 'prompt': (default) ask whether to initialize a new repo or open in the most recent repo
# - 'create': initialize a new repo
# - 'skip': open most recent repo
# - 'quit': exit Lazygit
notARepository: skip
 
git:
    paging:
        colorArg: always
        pager: delta --dark --paging=never --syntax-theme Dracula
